---
title: "SIRmodel"
date: "2029-02-18"
output: html_document
---

```{r setup, include = FALSE}
knitr:: opts_chunk$set(echo = TRUE)
library(tidyverse)
library(deSolve)
```

# Define parameters
c is the combine function
```{r params}
parameters <- c(beta= 0.3, gamma =0.2)
parameters
```

# Define initial values
I assumes that in a population of 10,000 people 1 person is infected.
```{r initVals}
initial_values <- c(S= 0.9999,
                    I= 0.0001,
                    R = 0)
initial_values
```

# Write model

```{r model}
SIRmodel <- function(t, state, parameters){
  with(as.list(c(state,parameters)), {
    #Rate of change equations
    dS <- -beta*S*I
    dI <- beta*S*I - gamma*I
    dR <- gamma * I
    
    #Combine rates of change into a list
    list(c(dS, dI, dR))
  })
}

```

# Pick time frame and intervals
```{r time}
time <- seq(0, 150, by= 1)
time
```

# Run the model

```{r run}
out <- ode(y = initial_values,
           times= time,
           func= SIRmodel,
           parms= parameters)

head(out)
```

# Git resources
https://user-guidance.analytical-platform.service.justice.gov.uk/github/rstudio-git.html#work-with-git-in-rstudio
https://happygitwithr.com/rstudio-git-github